[package]
name = "war-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
bevy = "0.10"
bevy_egui = "0.20"
big_space = "0.1.3"
big-brain = "0.17.0"
